# Generated by Django 3.1.3 on 2020-11-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weight_kg', models.FloatField()),
                ('weight_def', models.TextField()),
                ('series', models.IntegerField()),
                ('reps_s1', models.IntegerField()),
                ('reps_s2', models.IntegerField()),
                ('reps_s3', models.IntegerField()),
                ('reps_s4', models.IntegerField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.training')),
            ],
        ),
    ]
