# Generated by Django 3.1.3 on 2020-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20201109_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='series',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight_def',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight_kg',
            field=models.FloatField(blank=True),
        ),
    ]
