# Generated by Django 3.1.3 on 2020-11-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20201110_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='weight_def',
            new_name='weight_per',
        ),
    ]
