# Generated by Django 3.1.3 on 2020-11-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_auto_20201110_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='reps_s2',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps_s3',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps_s4',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps_s1',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
