# Generated by Django 3.1.3 on 2020-11-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_auto_20201111_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='reps_s1',
            new_name='reps',
        ),
    ]
