# Generated by Django 3.1.3 on 2020-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_training_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
