# Generated by Django 3.1.3 on 2020-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_auto_20201111_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('exercises', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.TextField(default='My weight training'),
        ),
    ]
