# Generated by Django 3.1.3 on 2020-11-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_auto_20201113_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.trainingplan'),
        ),
    ]
