# Generated by Django 3.1.3 on 2020-11-14 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0014_auto_20201114_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.trainingplan'),
        ),
    ]
